export const initialProfiles = [
  { id: 1, name: "Preetham", favoriteFood: "Chicken Biryani", favoriteColor: "Blue", likes: 0 },
  { id: 2, name: "Shiva Sai", favoriteFood: "South Indian food", favoriteColor: "Red", likes: 0 },
  { id: 3, name: "Pranadeep", favoriteFood: "Mutton ghosh", favoriteColor: "Purple", likes: 0 },
  { id: 4, name: "Emma Wilson", favoriteFood: "Pizza", favoriteColor: "Green", likes: 0 },
  { id: 5, name: "Liam Chen", favoriteFood: "Sushi", favoriteColor: "Black", likes: 0 },
  { id: 6, name: "Sophia Rodriguez", favoriteFood: "Tacos", favoriteColor: "Pink", likes: 0 },
  { id: 7, name: "Noah Kim", favoriteFood: "Korean BBQ", favoriteColor: "Navy", likes: 0 },
  { id: 8, name: "Ava Patel", favoriteFood: "Butter Chicken", favoriteColor: "Turquoise", likes: 0 },
  { id: 9, name: "Jackson Brown", favoriteFood: "Hamburger", favoriteColor: "Orange", likes: 0 },
  { id: 10, name: "Isabella Martinez", favoriteFood: "Paella", favoriteColor: "Yellow", likes: 0 },
  { id: 11, name: "Lucas Thompson", favoriteFood: "Pasta", favoriteColor: "Grey", likes: 0 },
  { id: 12, name: "Mia Johnson", favoriteFood: "Fish and Chips", favoriteColor: "Violet", likes: 0 },
  { id: 13, name: "Aiden Lee", favoriteFood: "Dim Sum", favoriteColor: "Maroon", likes: 0 },
  { id: 14, name: "Charlotte Davis", favoriteFood: "Caesar Salad", favoriteColor: "Coral", likes: 0 },
  { id: 15, name: "Ethan Singh", favoriteFood: "Naan", favoriteColor: "Indigo", likes: 0 },
  { id: 16, name: "Amelia White", favoriteFood: "Mac and Cheese", favoriteColor: "Teal", likes: 0 },
  { id: 17, name: "Oliver Wang", favoriteFood: "Hot Pot", favoriteColor: "Brown", likes: 0 },
  { id: 18, name: "Harper Garcia", favoriteFood: "Enchiladas", favoriteColor: "Gold", likes: 0 },
  { id: 19, name: "Sebastian Kumar", favoriteFood: "Dosa", favoriteColor: "Silver", likes: 0 },
  { id: 20, name: "Aria Ahmed", favoriteFood: "Shawarma", favoriteColor: "Bronze", likes: 0 },
  { id: 21, name: "Alexander Nguyen", favoriteFood: "Pho", favoriteColor: "Crimson", likes: 0 },
  { id: 22, name: "Evelyn Taylor", favoriteFood: "Shepherd's Pie", favoriteColor: "Lavender", likes: 0 },
  { id: 23, name: "Daniel Santos", favoriteFood: "Feijoada", favoriteColor: "Cyan", likes: 0 },
  { id: 24, name: "Victoria Chang", favoriteFood: "Ramen", favoriteColor: "Magenta", likes: 0 },
  { id: 25, name: "Henry Wilson", favoriteFood: "Steak", favoriteColor: "Burgundy", likes: 0 },
  { id: 26, name: "Luna Park", favoriteFood: "Bibimbap", favoriteColor: "Olive", likes: 0 },
  { id: 27, name: "Jack Anderson", favoriteFood: "Chicken Wings", favoriteColor: "Peach", likes: 0 },
  { id: 28, name: "Scarlett Liu", favoriteFood: "Dumplings", favoriteColor: "Ruby", likes: 0 },
  { id: 29, name: "Owen Murphy", favoriteFood: "Irish Stew", favoriteColor: "Emerald", likes: 0 },
  { id: 30, name: "Chloe Kim", favoriteFood: "Kimchi", favoriteColor: "Sapphire", likes: 0 },
  { id: 31, name: "Mason Lopez", favoriteFood: "Tamales", favoriteColor: "Pearl", likes: 0 },
  { id: 32, name: "Layla Shah", favoriteFood: "Biryani", favoriteColor: "Aqua", likes: 0 },
  { id: 33, name: "Elijah Brown", favoriteFood: "BBQ Ribs", favoriteColor: "Slate", likes: 0 },
  { id: 34, name: "Zoe Chen", favoriteFood: "Peking Duck", favoriteColor: "Rose", likes: 0 },
  { id: 35, name: "Gabriel Silva", favoriteFood: "Churrasco", favoriteColor: "Forest Green", likes: 0 },
  { id: 36, name: "Lily Tanaka", favoriteFood: "Tempura", favoriteColor: "Sky Blue", likes: 0 },
  { id: 37, name: "David Cohen", favoriteFood: "Falafel", favoriteColor: "Charcoal", likes: 0 },
  { id: 38, name: "Hannah Kim", favoriteFood: "Bulgogi", favoriteColor: "Mint", likes: 0 },
  { id: 39, name: "Joseph Gupta", favoriteFood: "Tandoori Chicken", favoriteColor: "Rust", likes: 0 },
  { id: 40, name: "Audrey Wu", favoriteFood: "Spring Rolls", favoriteColor: "Ivory", likes: 0 },
  { id: 41, name: "Christopher Lee", favoriteFood: "Pad Thai", favoriteColor: "Cherry", likes: 0 },
  { id: 42, name: "Bella Martinez", favoriteFood: "Quesadillas", favoriteColor: "Mustard", likes: 0 },
  { id: 43, name: "Andrew Zhang", favoriteFood: "Mapo Tofu", favoriteColor: "Tan", likes: 0 },
  { id: 44, name: "Grace Wilson", favoriteFood: "Lobster Roll", favoriteColor: "Plum", likes: 0 },
  { id: 45, name: "Ryan Patel", favoriteFood: "Samosas", favoriteColor: "Coffee", likes: 0 },
  { id: 46, name: "Nora Johnson", favoriteFood: "Clam Chowder", favoriteColor: "Mauve", likes: 0 },
  { id: 47, name: "William Cho", favoriteFood: "Japchae", favoriteColor: "Beige", likes: 0 },
  { id: 48, name: "Sophie Martin", favoriteFood: "Coq au Vin", favoriteColor: "Wine", likes: 0 },
  { id: 49, name: "Benjamin Lee", favoriteFood: "Tom Yum", favoriteColor: "Copper", likes: 0 },
  { id: 50, name: "Elena Rodriguez", favoriteFood: "Empanadas", favoriteColor: "Azure", likes: 0 }
];